"""make item_id nullable in all

Revision ID: f3dcf69e6abb
Revises: 
Create Date: 2025-07-03 22:36:52.805662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3dcf69e6abb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_Incoming')
    with op.batch_alter_table('Incoming', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.Integer(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_foreign_key('fk_incoming_item', 'StockList', ['item_id'], ['ID'])
        batch_op.drop_column('Item')

    with op.batch_alter_table('Outgoing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.Integer(), nullable=True))
        batch_op.alter_column('ID1',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('Qty',
               existing_type=sa.REAL(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('EmpName',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('EmpDep',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('OutgoingDate',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('Ticket',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.create_foreign_key('fk_outgoing_item', 'StockList', ['item_id'], ['ID'])
        batch_op.drop_column('Field1')
        batch_op.drop_column('Item')

    with op.batch_alter_table('Stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.Integer(), nullable=True))
        batch_op.alter_column('ID',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('AvaQty',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key('fk_stock_item', 'StockList', ['item_id'], ['ID'])
        batch_op.drop_column('Item')

    with op.batch_alter_table('StockList', schema=None) as batch_op:
        batch_op.alter_column('ID',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('Item',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('StockList', schema=None) as batch_op:
        batch_op.alter_column('Item',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('ID',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('Stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Item', sa.TEXT(), nullable=True))
        batch_op.drop_constraint('fk_stock_item', type_='foreignkey')
        batch_op.alter_column('AvaQty',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('ID',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('item_id')

    with op.batch_alter_table('Outgoing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Item', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('Field1', sa.TEXT(), nullable=True))
        batch_op.drop_constraint('fk_outgoing_item', type_='foreignkey')
        batch_op.alter_column('Ticket',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('OutgoingDate',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('EmpDep',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('EmpName',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('Qty',
               existing_type=sa.Integer(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('ID1',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('item_id')

    with op.batch_alter_table('Incoming', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Item', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('fk_incoming_item', type_='foreignkey')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('item_id')

    op.create_table('_alembic_tmp_Incoming',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('Qty', sa.INTEGER(), nullable=True),
    sa.Column('IncomingDate', sa.DATE(), server_default=sa.text('(CURRENT_DATE)'), nullable=True),
    sa.Column('item_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['StockList.ID'], name=op.f('fk_incoming_item')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
